config/routes.rb
Rails.application.routes.draw do
  
  # Devise
  ######################################
  devise_for :users, :controllers => { 
    # custom controllers
    omniauth_callbacks: 'omniauth_callbacks',
    confirmations: 'users/confirmations'
  }
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
  ######################################


  # Non-Devise Authentication Features
  ######################################
  resources :identities, only: [:destroy]
  resources :users, only: [:none] do
    get :edit_password
    patch :update_password

    get :edit_email
    patch :update_email

    post :cancel_email_change
    post :send_confirmation
  end
  ######################################


  root 'home#index'
end

app/controllers/home_controller.rb
class HomeController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  layout "application"

  def index
    @user = current_user
  end
end

app/views/home/index.html.erb
<h1>Home Page</h1>

<div style="border: 2px solid black; margin: 1em; padding: 0 1em 1em 1em;">
  <h3>User Actions</h3>
  <% if user_signed_in? %>

    <%= link_to 'Change Email', user_edit_email_path(current_user), class: 'btn btn-info' %>
    <%= link_to 'Edit Password', user_edit_password_path(current_user), class: 'btn btn-info' %>

    <% unless current_user.has_facebook_identity? %>
      <%= link_to 'Add Facebook', omniauth_authorize_path("user", "facebook"), class: 'btn btn-info' %>
    <% end %>


    <br>
    <p><b>User: </b><%= @user.to_json %></p>
    <% if @user.pending_reconfirmation? %>
      <div class="alert alert-warning">
        <p><b>Note:</b> You requested to change your email from <b><%= @user.email %></b> to <b><%= @user.unconfirmed_email %></b>. This change is 'pending' until you confirm it by clicking the link in the confirmation email we sent to your new email address.</p>
        <p>
          <b>If you did not receive the confirmation email</b>, please 
          <%= link_to 'click here', user_send_confirmation_path(@user), :method => :POST, class: 'btn btn-primary btn-xs' %> 
          to resend the confirmation instructions to your new email address.
          </p>
        <p>
          <b>If this was a mistake</b>, please 
          <%= link_to 'click here', user_cancel_email_change_path(@user), :method => :POST, class: 'btn btn-danger btn-xs' %> 
          to cancel this change.
        </p>
      </div>
    <% end %>

    <h4>Identities:</h4>
    <% @user.identities.each do |ident| %>
      <p>
        <%= link_to "X", ident, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
        <%= ident.to_json %>
      </p>

    <% end %>

  <% else %>
    <%= link_to "Sign In", new_user_session_path, class: 'btn btn-primary' %>
    <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-warning' %>
  <% end %>

</div>